online_exam/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from student import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name="admin"),
    path('student/' , include('student.urls')),
    path('logout/', views.user_logout, name="logout"),
    path('special/', views.special, name="special"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from student import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/' , views.login, name='login'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name="user_login"),
    path('questions/<int:exam_id>/', views.questions, name="questions"),
    path('finish/<int:exam_id>', views.finish, name="finish"),
    path('exams/', views.exams, name="exams"),
    path('ready/<int:exam_id>', views.ready, name="ready"),
    path('save_answers/', views.save_answers, name="save_answers"),
    path('fortest/', views.questions, name="fortest"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

# Create your models here.

class Exam(models.Model):
    class Meta():
        verbose_name_plural = 'Exams'
    name = models.CharField(blank = False, max_length = 1000)
    status = models.BooleanField(default=True)
    number_of_questions = models.IntegerField(blank = False)
    success_score = models.IntegerField()

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(blank=False, max_length=1000)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class E_Skill(models.Model):
    class Meta():
        verbose_name_plural = 'Exam_Skills'
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    ratio = models.PositiveIntegerField()

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.skill.name



class Question_Type(models.Model):
    name = models.CharField(blank=False, max_length=1000)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    title = models.TextField(blank = False, max_length = 2000)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    skill = models.ForeignKey(E_Skill, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    media = models.ImageField(blank=True, upload_to="question/")
    type = models.ForeignKey(Question_Type, on_delete=models.CASCADE)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    title = models.TextField(blank = False, max_length = 2000)
    is_correct = models.BooleanField(default=False)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + " - " + str(self.is_correct)


class Student_Exam(models.Model):
    #must set on login to exam
    student_name = models.CharField(max_length=200)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    #total mark must set on finish button
    total_mark = models.IntegerField()
    has_finish = models.BooleanField(default=False)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "name: "+self.student_name + ", Exam: " + str(self.exam) + ", mark: " + str(self.total_mark)


class Student_Answer(models.Model):
    #these fileds must set on click on any radio button
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    student_answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    student_exam = models.ForeignKey(Student_Exam, on_delete=models.CASCADE)
    skill = models.ForeignKey(E_Skill, on_delete=models.CASCADE)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return  str(self.student_exam) + ",   answer mark = " + str(self.student_answer)

student/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class': 'form_input'}))
    email = forms.EmailField(required=True, widget = forms.TextInput(attrs={'class': 'form_input'}))
    class Meta():
        model = User
        fields = ('username','email', 'password')
        help_texts = {
            'username': None,
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form_input'}),
        }


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class': 'form_input'}))
    class Meta():
        model = User
        fields = ('username', 'password')
        help_texts = {
            'username': None,
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form_input'}),
        }


class QuestionForm(forms.ModelForm):
    question = forms.CharField(label='')
    A = forms.CharField(widget=forms.RadioSelect, label='A')
    B = forms.CharField(widget=forms.RadioSelect, label='B')
    C = forms.CharField(widget=forms.RadioSelect, label='C')
    D = forms.CharField(widget=forms.RadioSelect, label='D')
    class Meta():
        model = Question
        fields = ('question','A', 'B', 'C', 'D')
        help_texts = {
            'username': None,
        }

student/views.py
from django.shortcuts import render, redirect
from student.forms import UserForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from student.models import Question, Exam, Student_Exam, Answer, Student_Answer, E_Skill
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json

# Create your views here.
def index(request):
        return render(request, 'student/index.html')

@login_required
def special (request):
    return HttpResponse("You are logged in, NICE")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request,user)
                if user.is_superuser:
                    return redirect('admin:index')
                return redirect('student:exams')

            else:
                return HttpResponse("Account Not Active")
        else:
            print("someone tried to login and faild")
            print("username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        login_form = LoginForm()
        return render(request,'student/login.html', {'login_form':LoginForm})

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            context = {'login_form': LoginForm}
            return render(request,'student/login.html', context)
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, 'student/registration.html', {'user_form':user_form,'registered':registered})

def exams(request):
    if request.user.is_authenticated:
        username = request.user.username
        exams = Exam.objects.all()
        return render(request,'student/exams.html', {'exams':exams, 'username':username})
    else:
        return HttpResponse("<h1> Login First </h1>")

def ready(request, exam_id):
    if request.user.is_authenticated:
        username = request.user.username
        if request.method == 'POST':
            return redirect('student:questions', exam_id)
        else:
            exam = Exam.objects.get(id=exam_id)
            try:
                has_finish_exam = Student_Exam.objects.filter(student_name = username, exam__id = exam_id).get()
                #return HttpResponse(has_finish_exam)
                if has_finish_exam.has_finish:
                    return redirect('student:finish', exam_id)
                else:
                    new_student_exam = Student_Exam.objects.filter(student_name=username, exam=exam).update(total_mark=0)

            except Student_Exam.DoesNotExist:
                new_student_exam = Student_Exam.objects.create(student_name = username, exam = exam, total_mark = 0)

            context = { 'exam':exam }
            return render(request, 'student/get_ready.html',context)
    else:
        return HttpResponse("<h1> Login First </h1>")

def questions(request, exam_id):
    if request.user.is_authenticated:
        username = request.user.username



        questions = []
        skills = E_Skill.objects.filter(exam__id=exam_id).prefetch_related('question_set').all()
        question = ''
        for skill in skills:
            questions += Question.objects.filter(skill__pk=skill.pk)[:int(skill.ratio)]
            #questions[skill.skill.name] = question
        #return HttpResponse(questions)
        #questions = tuple(questions)

        #questions = Question.objects.filter(exam_id=exam_id)
        answers = Answer.objects.filter(question__exam_id=exam_id)
        exam_name = questions[0].exam.name
        #paginator
        paginator = Paginator(questions, 1)
        page = request.GET.get('page')
        all_questions = paginator.get_page(page)
        context = {'questions': all_questions, 'answers':answers, 'username': username, 'exam_id': exam_id, 'exam_name': exam_name}
        return render(request, 'student/questions.html', context)

    else:
        return HttpResponse("<h1> Login First </h1>")

def finish(request, exam_id):
    if request.method == 'POST':
        exam = request.POST.get('exam', None)
    elif request.method == 'GET':
        exam = exam_id
    username = request.user.username

    student_exam = Student_Exam.objects.get(student_name=username, exam__id=exam)
    student_answers = Student_Answer.objects.filter(student_exam=student_exam)
    correct_answers = []
    questions_ids = []
    for answer in student_answers:
        questions_ids.append(answer.question.id)
        if answer.student_answer.is_correct:
            correct_answers.append(answer.student_answer)

    mark = (len(correct_answers)*100)/len(student_answers)

    finish_exam = Student_Exam.objects.filter(student_name=username, exam__id=exam).update(total_mark=mark, has_finish = True)
    is_pass = mark >= student_exam.exam.success_score
    all_answers = Answer.objects.filter(question__in=questions_ids)
    #return HttpResponse(all_answers)

    context = {'username' : username , 'student_answers':student_answers, 'all_answers':all_answers,'mark': int(mark), 'is_pass':is_pass, 'exam_name':student_exam.exam.name}
    return render(request, 'student/finish.html', context)




@csrf_exempt
def save_answers(request):
    if request.method == 'POST':
        exam = request.POST.get('exam', None)
        question = request.POST.get('question', None)
        answer = request.POST.get('answer', None)
        username = request.user.username

        student_question = Question.objects.get(id = question)
        student_answer = Answer.objects.get(title = answer)
        student_exam = Student_Exam.objects.get(student_name = username, exam__id = exam)
        skill = E_Skill.objects.get(id=1)

        try:
            st_answer = Student_Answer.objects.get(question = student_question, student_exam= student_exam)
            if answer != st_answer.student_answer:
                new_answer = Student_Answer.objects.filter(question= student_question, student_exam= student_exam, skill = skill).update(student_answer = student_answer)

        except Student_Answer.DoesNotExist:
            st_answer = None
            create_student_answer = Student_Answer.objects.create(
                question = student_question, student_answer = student_answer, student_exam = student_exam,skill = skill
            )

        return HttpResponse(username)
    elif request.method == 'GET':
        exam = request.GET.get('exam', None)
        question = request.GET.get('question', None)
        username = request.user.username

        student_question = Question.objects.get(id=question)
        student_exam = Student_Exam.objects.get(student_name=username, exam__id=exam)
        skill = E_Skill.objects.get(id=1)

        get_answer = Student_Answer.objects.filter(question=student_question, student_exam__exam__id = exam, student_exam__student_name=username, skill=skill)

        #print(exam)
        #print(question)
        #print(username)
        #print(get_answer)

        #context = { 'get_answer':get_answer[0].student_answer }
        print(get_answer[0].student_answer.title)
        data = {
            'answer_id': get_answer[0].student_answer.id,
            'answer_title' : get_answer[0].student_answer.title,
        }

        #print(get_answer[0].student_answer)
        #return HttpResponse(data)

        return JsonResponse(data, safe=False ,content_type='application/json')
        # return render(request, 'student/questions.html', context)

templates/student/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Online Exam</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Lingua project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
	<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/radio_style.css' %}">
</head>

<!-- Header -->
<header class="header">
	<!-- Header Content -->
	<div class="header_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="logo_container mr-auto">
							<a href="{% url 'index' %}">
								<div class="logo_text">Online Exam</div>
							</a>
						</div>
						<nav class="main_nav_contaner">
							<ul class="main_nav">
								<li><a href="{% url 'index' %}">Home</a></li>
								<!-- <li><a href="{% url 'admin:index' %}">Admin</a></li> -->

								{% if user.is_authenticated %}
								<li><a href="{% url 'student:exams' %}">Exams</a></li>
								<li><a href="{% url 'logout' %}">Logout</a></li>
								{% else %}
								<li><a href="{% url 'student:register' %}">Register</a></li>
								<li><a href="{% url 'student:user_login' %}">Login</a></li>
								{% endif %}

							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

<body>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% block javascript %}
{% endblock %}
{% block body_block %}
{% endblock %}
</body>

</html>

templates/student/exams.html
{% extends 'student/base.html' %}
{% load static %}
{% block body_block %}
<div style="position: absolute; width: 1300px; height: 500px; z-index: 15; top: 40%;left: 20%; margin: -100px 0 0 -150px;">
    <h2 class="section_title text-center">Upcoming Exams</h2>
</div>

<div style="position: absolute; width: 1300px; height: 500px; z-index: 15; top: 40%;left: 30%; margin: -100px 0 0 -150px;">
    <div class="container">
        <div class="row events_row">
            {% for exam in exams %}
            <div class="col-lg-4 event_col">
                <div class="event">
                    <div class="event_image"><img src="{% static 'images/event_2.jpg' %}" alt=""></div>
                    <div class="event_date d-flex flex-column align-items-center justify-content-center">
                        <div style="left:7%">{{ exam.date_time }}</div>
                    </div>
                    <div class="event_body d-flex flex-row align-items-center justify-content-start">
                        <div class="event_title"><a href="{% url 'student:ready' exam.id %}">{{ exam.name }}</a></div>
                        <div class="event_tag ml-auto">{{ exam.duration }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

templates/student/finish.html
{% extends 'student/base.html' %}
{% load static %}
{% block body_block %}
<html lang="en">
<body>
<div class="home">
	<div class="home_content">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					{% if is_pass %}
					<h1 class="home_title" style="color: green;"> congratulations {{ username }}</h1>
					<label style="color: green; font-size:22px;">you pass in {{exam_name}} exam, and your mark = {{ mark }}/100</label>
					{% else %}
					<h1 class="home_title" style="color: red;">We are sorry {{ username }}</h1>
					<label style="color: red; font-size:22px;">unfortunately you fail in {{exam_name}} exam, and your mark = {{ mark }}/100</label>
					{% endif %}
					<br><br>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="col-lg-6" style = "left: 10%">
	<div class="register_form_title"><br>
		<label style="color:black;font-size:25px;">Your Answers </label><br><br><br>
		{% for answer in student_answers %}
		<label style="color:black;font-size:18px;">{{ forloop.counter }}. {{ answer.question.title }}</label><br>
			{% for ans in all_answers %}
				{% if ans.question.id == answer.question.id %}
					{% if ans.is_correct %}
						<label style="color: green; font-size:15px;">&emsp;{{ ans.title }}</label><br>
					{% else %}
						{% if ans.title == answer.student_answer.title %}
							<label style="color: red; font-size:15px;">&emsp;{{ ans.title }}</label><br>
						{% else %}
							<label style="color: black; font-size:15px;">&emsp;{{ ans.title }}</label><br>
						{% endif %}
					{% endif %}
				{% endif %}
			{% endfor %}
		<br><br>
		{% endfor %}
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
	</div>
</div>
</body>
</html>


{% endblock %}

templates/student/fortest.html
{% extends 'student/base.html' %}
{% load static %}
{% block body_block %}
<html lang="en">
<body>
<div class="col-lg-6" style = "left: 10%">
	<div class="register_form_title"><br>
        <br><br><br><br><br><br><br>

		{% for skill, value in skill_question.items %}
		{% for v in value %}
		<label style="color:black;font-size:18px;">{{ v }} .{{ skill }} </label><br>
		{% endfor%}
		<br>
		{% endfor %}


		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
	</div>
</div>
</body>
</html>


{% endblock %}

templates/student/get_ready.html
{% extends 'student/base.html' %}
{% block body_block %}
<div style="position: absolute; width: 1000px; height: 500px; z-index: 15; top: 40%;left: 42%; margin: -100px 0 0 -150px;">
  <div class="col-lg-6">
      <div class="register_form_title">
        <h3> Click on Ready button for {{ exam.name }} when you are </h3><br><br>
        <form action="{% url 'student:ready' exam.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Ready" class="form_button trans_200">
        </form>
      </div>
  </div>
</div>

{% endblock %}

templates/student/index.html
{% extends 'student/base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en">
<body>

<div class="super_container">

	<div class="home">
		<div class="home_background" style="background-image:url({% static 'images/index_background.jpg' %})"></div>
		<div class="home_content">
			<div class="container">
				<div class="row">
					<div class="col text-center">
						<h1 class="home_title">Learn Languages Easily</h1>
						<div class="home_button trans_200"><a href="{% url 'student:register' %}">get started</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>






{% endblock %}

templates/student/login.html
{% extends 'student/base.html' %}
{% block body_block %}
<div style="position: absolute; width: 1000px; height: 500px; z-index: 15; top: 40%;left: 42%; margin: -100px 0 0 -150px;">
  <div class="col-lg-6">
    <div class="register_form_container">
      <div class="register_form_title">
        <h1> Please Login</h1><br><br>
        <form action="{% url 'student:user_login' %}" method="post">
          {% csrf_token %}
          {{ login_form.as_p }}
          <br>
          <input type="submit" value="Login" class="form_button trans_200">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/student/questions.html
{% extends 'student/base.html' %}

{% block javascript %}
<script>

$(function () {
  	$('input').on('click', function () {
  		var answer = $(this).val();
  		console.log(answer)
        $.ajax({
        	type: 'POST',
            url: '{% url 'student:save_answers' %}',
            data: {
            	exam : $("input[name=exam]").val(),
            	question : $("input[name=question]").val(),
            	answer : answer,
            },
        });
    });
});

$(document).ready(function(){
	$.ajax({
	    type: 'GET',
		url: '{% url 'student:save_answers' %}',
        context: document.body,
        data: {
            	exam : $("input[name=exam]").val(),
            	question : $("input[name=question]").val(),
            },
        dataType : "json",
		success: function(data){
			var answer_id = data['answer_id']
			var answer_title = data['answer_title']
            $('input[id="' + answer_id + '"][value="' + answer_title + '"]').attr('checked', true);
        }});
});

</script>
{% endblock %}


{% block body_block %}
{% load static %}

<div class="col-lg-6" style = "left: 10%">
      <div class="register_form_title"><br><br><br><br>
		  <h4>Welcome to Examination, {{ username }}</h4>
		  <h5>{{ exam_name }} Exam</h5>
		  <br><br>
			<!-- questions.1.question.id  -->
		  <form id="questions_form" action="{% url 'student:finish' exam_id %}" method="POST">
			  {% csrf_token %}

			  <input class="hidden" name="exam" value="{{ exam_id  }}"></input>
			  {% for question in questions %}
			  <br>
			  <h5>{{ question.skill }}</h5>
			  <br><br>
			  <input class="hidden" name="question" value="{{ question.id }}" style="color:black;font-size:20px;"></input>{{ questions.number }}. {{ question }}<br>

			  {%  for answer in answers %}
			  {% if answer.question.id == question.id %}

			  <input type="radio" id="{{ answer.id }}" name="answer" value="{{ answer.title }}"/>

			  {% if answer.is_correct %}
			  <label><span style="color: black; font-size:14px;">{{ answer.title }}</span></label><br>
			  {% else %}
			  <label><span style="color: black; font-size:14px;">{{ answer.title }}</span></label><br>
			  {% endif %}


			  {% endif %}
			  {% endfor %}
			  {% endfor %}
			  <br><br><br>

			  {% if not questions.has_next %}
			  <div class="register_form_title">
				  <input type="submit" name='Finish' value="Finish" class="form_button trans_200">
			  </div>
			  {% endif %}

			  <br><br><br><br><br><br>


			  <div class="row">
				  <div class="col-md-12">
					  {% if questions.has_other_pages %}
					  <ul class="pagination">
						  {% if questions.has_previous %}
						  <li class="page-item">
							  <a href="?page={{ questions.previous_page_number }}" class="page-link">&laquo;</a>
						  </li>
						  {% else %}
						  <li class="page-item disabled">
							  <a class="page-link">&laquo;</a>
						  </li>
						  {% endif %}
						  {% for i in questions.paginator.page_range %}
						  {% if questions.number == i %}
						  <li class="page-item active">
							  <a class="page-link">{{i}}</a>
						  </li>
						  {% else %}
						  <li class="page-item">
							  <a href="?page={{ i }}" class="page-link">{{i}}</a>
						  </li>
						  {% endif %}
						  {% endfor %}
						  {% if questions.has_next %}
						  <li class="page-item">
							  <a href="?page={{ questions.next_page_number }}" class="page-link">&raquo;</a>
						  </li>
						  {% else %}
						  <li class="page-item disabled">
							  <a class="page-link">&raquo;</a>
						  </li>
						  {% endif %}
					  </ul>
					  {% endif %}
				  </div>
			  </div>


		  </form>
	  </div>
</div>
{% endblock %}

templates/student/registration.html
{% extends 'student/base.html' %}
{% load static %}

{% block body_block %}
<br><br><br><br><br><br><br>
<div style="position: absolute; width: 1300px; height: 500px; z-index: 15; top: 40%;left: 40%; margin: -100px 0 0 -150px;">
  <div class="col-lg-6">
    <div class="register_form_container">
      <div class="register_form_title">
        {% if registered %}
        <h1>thank you for registering</h1>
        {% else %}
        <h2>Register Now!</h2><br>

        <form method="post" id="RegisterForm" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          <br>
          <input type="submit" name="" value="Register" class="form_button trans_200">
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}